name: Create Azure Container Registry with ARM Template

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch

jobs:
  create-acr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Azure
        uses: azure/login@v4
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Deploy ACR with ARM Template
        uses: azure/arm-deploy@v2
        with:
          scope: "subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          template: "./acr.json"
          deploymentName: "Pnode23srk"
