name: Create Azure Container Registry with ARM Template

on:
  workflow_dispatch:
jobs:
  create-acr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Azure
        uses: azure/login@v1.6.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: create resource group
        uses: Azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/bash
            az group create --name ${{ inputs.ResourceGroupName }}-RG --location ${{ inputs.ResourceGroupLocation }}
            echo "Azure resource group created"
    
      - name: Deploy ACR with ARM Template
        uses: azure/arm-deploy@v1.0.9
        with:
          subscriptionId: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          resourceGroupName: ${{ inputs.ResourceGroupName }}-RG
          template: "./acr.json"
          deploymentName: "Pnode23srk"
